[package]
name = "cargo-update"
description = "A cargo subcommand for checking and applying updates to installed executables"
documentation = "https://rawcdn.githack.com/nabijaczleweli/cargo-update/doc/cargo_update/index.html"
repository = "https://github.com/nabijaczleweli/cargo-update"
readme = "README.md"
keywords = ["cargo", "update", "plugin", "subcommand"]
categories = ["development-tools::cargo-plugins"]
license = "MIT"
build = "build.rs"
# Remember to also update in appveyor.yml
version = "2.5.0"
# Remember to also update in man/*.md
authors = ["nabijaczleweli <nabijaczleweli@gmail.com>",
           "Yann Simon <yann.simon.fr@gmail.com>",
           "ven <vendethiel@hotmail.fr>",
           "Cat Plus Plus <piotrlegnica@piotrl.pl>",
           "Liigo <liigo@qq.com>",
           "azyobuzin <azyobuzin@users.sourceforge.jp>",
           "Tatsuyuki Ishi <ishitatsuyuki@gmail.com>",
           "Tom Prince <tom.prince@twistedmatrix.com>",
           "Mateusz Mikuła <mati865@gmail.com>",
           "sinkuu <sinkuupump@gmail.com>",
           "Alex Burka <aburka@seas.upenn.edu>",
           "Matthias Krüger <matthias.krueger@famsik.de>",
           "Daniel Holbert <dholbert@cs.stanford.edu>",
           "Jonas Bushart <jonas@bushart.org>"]
exclude = ["*.enc"]


# Note: don't bump dependencies unless necessary to keep building on old rustc versions
[dependencies]
# https://travis-ci.org/nabijaczleweli/cargo-update/jobs/619241497#L222 broke 1.35.0 with smallvec 1.0.0,
# required by unicode-normalization 0.1.11. Previous working build is
# https://travis-ci.org/nabijaczleweli/cargo-update/jobs/611381166#L271 with unicode-normalization 0.1.9
# h/t to @elichai in https://github.com/nabijaczleweli/cargo-update/issues/119#issuecomment-560116619
# for suggesting using a `=` dep instead of a patch
unicode-normalization="=0.1.9"
serde_derive = "1.0"
lazy_static = "1.4"
array_tool = "1.0"
tabwriter = "1.1"
lazysort = "0.2"
regex = "1.3"
serde = "1.0"
git2 = "0.11"
clap = "2.33"
dirs = "2.0"
json = "0.11"
toml = "0.5"
url = "2.1"

[dependencies.semver]
version = "0.9"
features = ["serde"]

[build-dependencies]
embed-resource = "1.3"


[[bin]]
name = "cargo-install-update"
path = "src/main.rs"
test = false
doc = false

[[bin]]
name = "cargo-install-update-config"
path = "src/main-config.rs"
test = false
doc = false
